# Generated by Django 3.1.4 on 2020-12-14 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(choices=[('Die', 'Mort'), ('Alive', 'Vivant)')], max_length=10)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suivie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dehydration', models.CharField(choices=[('0', 'low'), ('1', 'medium'), ('2', 'high')], max_length=10)),
                ('selles', models.CharField(choices=[('0', 'low'), ('1', 'medium'), ('2', 'high')], max_length=10)),
                ('vomissements', models.CharField(choices=[('0', 'low'), ('1', 'medium'), ('2', 'high')], max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('photo', models.ImageField(null=True, upload_to='photosPatients/')),
                ('age', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('admissionDate', models.DateTimeField()),
                ('admissionID', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('exitStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.exitstatus')),
                ('suivie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.suivie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
