# Generated by Django 3.1.4 on 2020-12-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivie',
            name='dehydration',
            field=models.CharField(choices=[('0', 'very-low'), ('1', 'low'), ('2', 'medium'), ('3', 'high'), ('4', 'very-high')], max_length=10),
        ),
        migrations.AlterField(
            model_name='suivie',
            name='selles',
            field=models.CharField(choices=[('0', 'very-low'), ('1', 'low'), ('2', 'medium'), ('3', 'high'), ('4', 'very-high')], max_length=10),
        ),
        migrations.AlterField(
            model_name='suivie',
            name='vomissements',
            field=models.CharField(choices=[('0', 'very-low'), ('1', 'low'), ('2', 'medium'), ('3', 'high'), ('4', 'very-high')], max_length=10),
        ),
    ]
